In [ ]:
# Numpy module 
# 다차원배열 그리고 2차원 matrix 연산을 쉽고 빠르게 하기 위해서 사용
# ndarray
# ndarray의 특징, 속성
# ndarray의 생성방법
# random관련된 생성방법과 특수한 기능들(메소드들)
# indexing, slicing
# boolean indexing, fancy indexing

In [7]:
# ndarray의 사칙연산(일반적인 연산)
# ndarray의 shape이 같아야 해요!

import numpy as np

# arr1 = np.array([1,2,3])  # (3,)
# arr2 = np.array([4,5,6])  # (3,)
# print(arr1 + arr2)   # [5 7 9]

# 만약 shape이 다르다면..
# arr1 = np.array([1,2,3,4])  # (4,)
# arr2 = np.array([4,5,6])    # (3,)
# print(arr1 + arr2)          # 오류

# 하지만 shape이 다를때도 만약 shape을 맞출 수 있으면 연산이 가능
# broadcasting이 발생해서 두 개의 ndarray의 shape을 똑같이 맞춰요!
# arr1 = np.array([1,2,3,4])  # (4,)
# print(arr1 + 1)           # broadcasting

# 다양한 경우
# arr1 = np.array([1,2,3,4,5,6])  # (6,)
# arr2 = np.array([4,5,6])        # (3,)
# arr1 + arr2                 # 오류

# arr1 = np.array([[1,2,3], [4,5,6]])  # (2,3)
# arr2 = np.array([4,5,6])             # (3,)
# arr1 + arr2                 # 가능

# 행렬곱연산(matrix 곱연산)
arr1 = np.array([[1,2,3], [4,5,6]])    # (2,3)
arr2 = np.array([[4,5], [6,7], [8,9]]) # (3,2)
# 행렬곱연산의 결과는 당연히 (2,2)
print(np.matmul(arr1,arr2))

[[ 40  46]
 [ 94 109]]


In [9]:
# 전치행렬(transpose)

import numpy as np

arr = np.array([[1,2,3], [4,5,6]])  # (2,3)
print(arr)

print(arr.T)  # (3,2)

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


In [4]:
# iterator(반복자)를 이용한 반복문 처리
# for문을 이용해서 반복처리를 하는데 
# ndarray는 while문과 iterator를 이용해서 반복처리는 방식을 선호.

import numpy as np

# arr = np.array([1, 2, 3, 4, 5]) # (5,)

# for문을 이용한 반복처리
# for tmp in arr:
#     print(tmp)
    
# 1차원 ndarray에 대해서 iterator를 이용해 반복처리
arr = np.array([1, 2, 3, 4, 5]) # (5,)

# iterator 객체를 하나 얻어와요!
# iterator 객체로부터 index를 추출할수 있어요!
my_iter = np.nditer(arr, flags=['c_index'])

while not my_iter.finished:
    
    idx = my_iter.index
    print(arr[idx])   # 출력
    my_iter.iternext()

1
2
3
4
5


In [8]:
# 2차원 ndarray에 반복처리

import numpy as np

# arr = np.array([[1,2,3], [4,5,6]])  # (2,3)

# for tmp1 in range(arr.shape[0]):
#     for tmp2 in range(arr.shape[1]):
#         print(arr[tmp1, tmp2])

arr = np.array([[1,2,3], [4,5,6]])  # (2,3)

my_iter = np.nditer(arr, flags=['multi_index'])

while not my_iter.finished:
    
    idx = my_iter.multi_index
    print(idx)
    print(arr[idx])
    my_iter.iternext()

(0, 0)
1
(0, 1)
2
(0, 2)
3
(1, 0)
4
(1, 1)
5
(1, 2)
6


In [20]:
# 다양한 집계함수와 axis개념이 나와요!

import numpy as np

# arr = np.arange(1,7,1).reshape(2,3)
# print(arr)      # [[1 2 3]
#                 #  [4 5 6]]
    
# ndarray 데이터에 대한 합을 구할 수 있어요!    
# print(np.sum(arr))  # 21   => Numpy가 제공하는 함수를 이용
# print(arr.sum())    # 21   => ndarray가 가지고 있는 메소드를 이용
# print(arr.mean())   # 3.5
# print(arr.max())   # 6
# print(arr.min())   # 1
# print(arr.argmax())   # 5
# print(arr.std())   # 표준편차 => 1.707825127659933

# axis 개념에 대해서 알아보아요!!!
# numpy는 집계함수를 이용할 때 axis를 명시하지 않으면 전체를 대상으로 연산 수행

arr = np.arange(1,7,1).reshape(2,3)
print(arr)      # [[1 2 3]
                #  [4 5 6]]
print(arr.sum(axis=0))   # [5 7 9]
print(arr.sum(axis=1))   # [ 6 15]


[[1 2 3]
 [4 5 6]]
[5 7 9]
[ 6 15]


In [23]:
# 간단한 연습문제

import numpy as np

arr = np.arange(1,17,1).reshape(4,4)
print(arr)

# 이 안에 10보다 큰 수는 몇개 있나요?  6개!!
# ?? => Boolena Indexing을 이용

print((arr > 10).sum())

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
6


In [ ]:
# ndarray의 정렬, 연결, 삭제, CSV파일 로딩
# 일반적으로 ndarray로 이작업을 하지 않아요!
# pandas로 처리해요!
# 우리 pandas에 대해서 알아보아요!